# -*- coding: utf-8 -*-
"""Hangman-game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJ8F__6u-nYz2JWgLr9yPJoFxQ_EkndG
"""

import random

WORDS = ["python", "notebook", "colab", "hangman", "simple"]  # exactly 5 words
MAX_WRONG = 6  # limit incorrect guesses

def masked_word(secret, guessed):
    return " ".join([c if c in guessed else "_" for c in secret])

def get_letter(already_tried):
    while True:
        g = input("Guess a letter: ").strip().lower()
        if len(g) != 1 or not g.isalpha():
            print(" Please enter a single alphabetic letter.")
            continue
        if g in already_tried:
            print(" You already tried that letter. Pick another.")
            continue
        return g

def play_once():
    secret = random.choice(WORDS)
    guessed = set()
    tried = set()
    wrong = set()
    remaining = MAX_WRONG

    print("\n🎯 Welcome to Hangman!")
    print(f"I've picked a word with {len(secret)} letters.")
    print(masked_word(secret, guessed))

    while remaining > 0:
        print(f"\nWrong guesses left: {remaining}")
        if wrong:
            print("Wrong letters:", ", ".join(sorted(wrong)))
        guess = get_letter(tried)
        tried.add(guess)

        if guess in secret:
            guessed.add(guess)
            print("✅ Good guess!")
        else:
            wrong.add(guess)
            remaining -= 1
            print("❌ Nope.")

        print("Word:", masked_word(secret, guessed))

        # win condition
        if all(c in guessed for c in set(secret)):
            print("\n🏆 You win! The word was:", secret)
            return

    # lose condition
    print("\n💀 Out of guesses. The word was:", secret)

def main():
    while True:
        play_once()
        again = input("\nPlay again? (y/n): ").strip().lower()
        if again != "y":
            print("Thanks for playing! 👋")
            break

if __name__ == "__main__":
    main()